name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to vps perso
      uses: appleboy/ssh-action@master
      with:
        username: maxim
        host: 51.210.8.134
        port: 2030
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /home/maxim/production/wow-scrapper/.github && ./server_deploy.sh'