name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to vps perso
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host:  ${{ secrets.SSH_HOST }}
        port:  ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /home/maxim/production/wow-scrapper/.github && sudo sh ./deploy.sh'